Fix/track
ovh-ux/ng-ovh-line-diagnostics pull request #13
Opened 2018-09-21 14:36 UTC by euhmeuh

2018-09-21 15:08 UTC, FredericEspiau approved these changes

2018-09-24 14:25 UTC, marie-j approved these changes

2018-09-25 06:58 UTC, antleblanc requested changes

2018-09-25 06:58 UTC, antleblanc commented on src/ovh-angular-line-diagnostics/ovh-angular-line-diagnostics.controller.js
> +    constructor ($interval, $q, $state, $timeout, $translate, atInternet, LineDiagnostics, LineDiagnosticFactory, Toast, DIAGNOSTICS_CONSTANTS) {
Could you please remove those unused injections `$q, $state`?

2018-09-25 13:09 UTC, antleblanc commented
I will generate the `dist` during the release process (according to my previous request ;))

2018-09-25 13:13 UTC, merged