refactor: update stack with component-rollup-config
ovh-ux/ng-ovh-line-diagnostics pull request #19
Opened 2019-08-20 14:54 UTC by cbourgois

## refactor: update stack with component-rollup-config

### Description of the Change

* use `@ovh-ux/component-rollup-config` to build the package
* remove use of bower
* clean dependencies
* update eslint config
* add missing assets
BREAKING CHANGE: the package is now `@ovh-ux/ng-ovh-line-diagnostics`. The module
is now `ngOvhLineDiagnostics`

698c879 — refactor: update stack with component-rollup-config

# To Do : 

* [ ] rename repository to `ng-ovh-line-diagnostics`

https://github.com/ovh-ux/manager/issues/188

2019-08-20 15:19 UTC, antleblanc requested changes
Well done!

Just a quick note regarding some parts that still mention `bower`.

2019-08-20 15:19 UTC, antleblanc commented on src/provider.js
> +  let translationPath = '../bower_components/ovh-angular-line-diagnostics/dist';
No more needed?

2019-08-21 08:29 UTC, cbourgois commented on src/provider.js
> +  let translationPath = '../bower_components/ovh-angular-line-diagnostics/dist';
Nope, I have to remove it.

2019-08-21 14:53 UTC, cbourgois commented on src/provider.js
> +  let translationPath = '../bower_components/ovh-angular-line-diagnostics/dist';
Resolved.

2019-08-21 15:12 UTC, antleblanc approved these changes

2019-08-21 15:12 UTC, antleblanc commented on package.json
>    "dependency": {},
This entry could be removed I guess.

2019-08-22 13:26 UTC, cbourgois commented on package.json
>    "dependency": {},
Removed 👍

2019-08-22 13:43 UTC, antleblanc approved these changes

2019-08-22 13:43 UTC, merged